services:
  appweb:
    build:
      context: ./Back_Front
      dockerfile: Dockerfile.dev
    volumes:
      - ./Back_Front:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - ./Back_Front/.env.local
